services:
  backend:
    build: .
    working_dir: /app/backend
    command: uvicorn backend:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - MODELS_DIR=models

  frontend:
    build: .
    working_dir: /app/frontend
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend 